language: java
jdk:
 - oraclejdk8

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install

addons:
   sonarcloud:
       organization: "sweihmws2018-19"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn assembly:assembly -Dfile.encoding=UTF-8 -DdescriptorId=jar-with-dependencies package